### ISSUE TITLE
aggregateNeighbors produces NA

### ISSUE THREAD

**Issue by roskcl** [BodenmillerGroup/imcRtools#101]
Hello,
I am running the Cellular neighborhood analysis from the steinbock pipeline. However, when I aggregateNeighbors by expression NAs are produced for some cells like in the image below. This stops kmeans clustering from working for neighbourhood detection. Do you have any suggestion on what could be done to overcome this issue? Would substituting the NAs for 0s be acceptable?
Thank you very much for your help!

![image](https://user-images.githubusercontent.com/41114163/232112972-c18aa6f8-5712-4d42-8e07-84d15e1d7793.png)

**Comment by nilseling** [comment]
Hi @roskcl 

yes, those cells don't have any neighboring cells. You can replace the NAs with 0 to perform the clustering.
