### ISSUE TITLE
Error when executing read_steinbock command

### ISSUE THREAD

**Issue by marleneweiss** [BodenmillerGroup/imcRtools#106]
Hi, 
I get the following error when trying to load my data through the read_steinbock command. I checked the folders many times and can't find the error. Loading data had previously worked for a different set of data without any problems.

Error in DataFrame(..., check.names = FALSE) :
different row counts implied by arguments

A hint towards solving the issue is highly appreciated!

Thank you,
Marlene

**Comment by nilseling** [comment]
Hi @marleneweiss 
which version of `imcRtools` are you using? Could you potentially send me the data (intensities, regionprops, neighbors) at nils.eling@uzh.ch?

**Comment by nilseling** [comment]
Hi @marleneweiss 

when looking at the intensities of `TMA_2_14_22_026` and `TMA_2_14_22_027` you can see that these files only contain 33 instead of 37 channels. I'm not sure how this happened - my guess is that for these two acquisitions only a subset of the channels were acquired. The `read_steinbock` function assumes that all acquisitions are acquired with the same panel. I will try to add more verbose error messages in cases like this. So far I have not come across this setting.

**Comment by marleneweiss** [comment]
Hi Nils,


thank you for looking into this and immediately finding the issue! I am also not sure how this happened since all samples were aquired with the same panel - I guess I will generate the files once more through steinbock and hope that they will show all 37 channels.


Best,

Marlene



Dr. med. Marlene Weiß

Assistenzärztin

Medizinische Klinik m.S. Nephrologie u. Internistische Intensivmedizin

Charité Universitätsmedizin Berlin

Campus Virchow Klinikum | Augustenburger Platz 1, 13353 Berlin

Tel.: 030-450614768


________________________________
Von: Nils Eling ***@***.***>
Gesendet: Montag, 22. Mai 2023 08:45:43
An: BodenmillerGroup/imcRtools
Cc: Weiß, Marlene; Mention
Betreff: [ext] Re: [BodenmillerGroup/imcRtools] Error when executing read_steinbock command (Issue #106)


Hi @marleneweiss<https://github.com/marleneweiss>

when looking at the intensities of TMA_2_14_22_026 and TMA_2_14_22_027 you can see that these files only contain 33 instead of 37 channels. I'm not sure how this happened - my guess is that for these two acquisitions only a subset of the channels were acquired. The read_steinbock function assumes that all acquisitions are acquired with the same panel. I will try to add more verbose error messages in cases like this. So far I have not come across this setting.

**Comment by nilseling** [comment]
Could you open them in MCD viewer and check if all ROIs contain 37 channels? Otherwise `steinbock` won't be able to rescue this.

**Comment by marleneweiss** [comment]
Yes, I will double check.


Best,

Marlene



Dr. med. Marlene Weiß

Assistenzärztin

Medizinische Klinik m.S. Nephrologie u. Internistische Intensivmedizin

Charité Universitätsmedizin Berlin

Campus Virchow Klinikum | Augustenburger Platz 1, 13353 Berlin

Tel.: 030-450614768


________________________________
Von: Nils Eling ***@***.***>
Gesendet: Montag, 22. Mai 2023 08:59:24
An: BodenmillerGroup/imcRtools
Cc: Weiß, Marlene; Mention
Betreff: [ext] Re: [BodenmillerGroup/imcRtools] Error when executing read_steinbock command (Issue #106)


Could you open them in MCD viewer and check if all ROIs contain 37 channels? Otherwise steinbock won't be able to rescue this.

**Comment by nilseling** [comment]
Closing this assuming it has been resolved. In the future please close issues that don't require more comments.
