### ISSUE TITLE
Select neighbours

### ISSUE THREAD

**Issue by aleixrius** [BodenmillerGroup/imcRtools#123]
Short question.
I defined the neighbours in the Steinbock step. With imcRtools I defined different cell clusters. Is it possible now to select (in a new spe object) all cells neighbouring a certain cell cluster?

Thanks!

Best,
Aleix

**Comment by SchulzDan** [comment]
Hi @aleixrius,
short answer, yes of course. Long answer: I do not think that this is an issue that actually belongs on github. This is rather a request for coding help it seems for which stackoverflow may be more suited. If you want to get into it, I recommend that you look into the colPairs of your spe object. These are selfhits and contain the information which cell neighbors which other cell. 
here some starting hints:
`int_dat <- as.data.frame(colPair(sce, "knn_interaction_graph"))
int_dat$celltype_from <- sce$CellType[int_dat$from]
int_dat$celltype_to <- sce$CellType[int_dat$to]`

you can continue to create a dataframe with information about interacting cells in your data and then filter it for the interactions you are looking for, get the ids of the cells and then subset your spe object to only those IDs.

I will close this issue.
Best,
Daniel

**Comment by aleixrius** [comment]
Great! Thanks so much for your help!

Best regards,
Aleix
