### ISSUE TITLE
Functions for interfacing with steinbock data

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imcRtools#14]
As discussed and described in https://github.com/BodenmillerGroup/steinbock/issues/12, add functions to imcRtools for interfacing with steinbock. Specifically, add functions for importing/exporting single-cell data from/to [steinbock object data format](https://bodenmillergroup.github.io/steinbock/specs/file-types/#object-data) (preprocessed [example data](https://github.com/BodenmillerGroup/TestData) will be provided shortly). When adding support for spillover compensation on the pixel-level rather than the single-cell-level as described in https://github.com/BodenmillerGroup/imcRtools/issues/12, ensure read/write functionality for TIFF images.

**Comment by jwindhager** [comment]
TestData asset now available: https://github.com/BodenmillerGroup/TestData/releases/download/v1.0.3/210308_ImcTestData_steinbock.tar.gz

**Comment by nilseling** [comment]
Great, thanks! I'll add it next week or so. Is the export functionality important? Do you plan on using steinbock for further processing?

**Comment by jwindhager** [comment]
Wonderful, thank you so much!

Re export: Not important at the moment for single cell data, as the
downstream processing tasks implemented in steinbock do not take into
account intensity information. This may change in the future, though, for
example when support for graph file formats such as GraphML (which supports
vertex attributes) is needed. I'd say that import is enough for now, but
good to keep in mind that export may be required in the future.

In general, I don't see steinbock as a framework for data analysis at this
point.

Re pixel-level compensation: here the export (to TIFF) would be crucial, as
this happens before single cell data extraction, which is a core
functionality of steinbock.

**Comment by nilseling** [comment]
A reader function has now been added in #15. The tiff export will happen in `cytomapper`.
