### ISSUE TITLE
Add simple spatial graph builders

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/imcRtools#18]
Add knn-based, expansion-based (BiocNeighbours) or other (Delauney, etc) graph construction wrappers until I find a better package to handle SingleCellExperiment and SpatialExperiment objects

**Comment by jwindhager** [comment]
Or add support for loading edge lists from disk :innocent:

**Comment by nilseling** [comment]
From disk it has to go via `read_steinbock`. Just to make sure that vertices in the graph match to cells in the object. Or do you have an example of external edge lists that need support?

**Comment by nilseling** [comment]
Added in #23
