### ISSUE TITLE
plotSpatial function

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/imcRtools#24]
the Y axis in this function is inverted. should be something like: y = max(y)-y

**Comment by nilseling** [comment]
In fact the coordinate system on the IMC is inverted. You can add `+ scale_y_reverse ` to flip the y axis

**Comment by nilseling** [comment]
We need to add this to the vignette

**Comment by nilseling** [comment]
Better add this as parameter in the function

**Comment by jwindhager** [comment]
I just saw this - whether IMC coordinates are inverted can be extracted from MCD metadata based on `ROI(Start/End)(X/Y)PosUm` (and thus may change with future Fluidigm software versions), see for example [here](https://github.com/BodenmillerGroup/slidescanner/blob/6836bf52c68afe240ce77f67cbdffb695f368dca/slidescanner/utils/io.py#L124-L128)

**Comment by nilseling** [comment]
These are now parameters in [plotSpatial](https://bodenmillergroup.github.io/imcRtools/reference/plotSpatial.html) added in #31
