### ISSUE TITLE
Change in steinbock graph file format

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imcRtools#32]
With steinbock v0.7.0, the graph file format was adapted, to account for additional information associated with edges (namely, distances). The new format is documented [here](https://bodenmillergroup.github.io/steinbock/v0.7.0/specs/file-types/#spatial-object-graphs). Support for the old format can be dropped, as steinbock is still in its early stages of community adoption.

**Comment by jwindhager** [comment]
Also, the default "graph" directory changed to `neighbors` in v0.7.1

**Comment by nilseling** [comment]
Thanks! All the way up on my todo list ;) Could you please rebuild the TestData?

**Comment by jwindhager** [comment]
On it right now :)

**Comment by nilseling** [comment]
Adjusted in #34
