### ISSUE TITLE
Read steinbock metadata from images.csv

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imcRtools#38]
With steinbock v0.8.0, as requested by @SchulzDan, image metadata is written to `images.csv` upon preprocessing. As discussed offline, this metadata should be made available to the imcRtools user through the `SingleCellExperiment` (please discuss with @SchulzDan what information is relevant). 

Please note that the existence of an `images.csv` file is optional (the user may choose to not use steinbock for preprocessing and to instead directly start from TIFF files) and that the filename can be modified by the user. If such a file is present, it can be expected to adhere to the [steinbock "image information" file specifications](https://bodenmillergroup.github.io/steinbock/latest/file-types/#image-information).

Additional columns that are added specifically when preprocessing IMC data (currently undocumented):
- `source` (the raw mcd/txt file name)
- `recovered` (`True` if an mcd acquisition was recovered from the corresponding txt file, otherwise `False`)
- `acquisition_id`
- `acquisition_description`
- `acquisition_posx_um`
- `acquisition_posy_um`
- `acquisition_width_um`
- `acquisition_height_um`

The test data in https://github.com/BodenmillerGroup/TestData has been updated.

**Comment by nilseling** [comment]
Hey @jwindhager,  is the `images.csv` file written out by default? I mean in case the user pre-processes images using steinbock.

**Comment by jwindhager** [comment]
Yes it is, if the user uses Steinbock IMC preprocessing functionality (specifically, `steinbock preprocess imc images`)

**Comment by nilseling** [comment]
Aight! What about other multi-channel images? From the docs it looks like it's always written out with the columns you documented

**Comment by nilseling** [comment]
Done in 6299fec84e4be05e7cd7c67abc654ca6f222acad

**Comment by jwindhager** [comment]
> Aight! What about other multi-channel images? From the docs it looks like it's always written out with the columns you documented

Currently, preprocessing functionality is provided for IMC only
