### ISSUE TITLE
Expand unit tests and validity checks

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/imcRtools#42]
For read_steinbock check that either all or none of the regionprops and neighbor files are present

**Comment by SchulzDan** [comment]
new test for empty files

**Comment by nilseling** [comment]
For `read_steinbock`, check that `images.csv` contain the same amount of entries as `intensities` etc files.

**Comment by nilseling** [comment]
Also check that ObjectNumbers, channels, etc match

**Comment by nilseling** [comment]
Done in #115
