### ISSUE TITLE
testInteractions() error

### ISSUE THREAD

**Issue by erikgerdtsson** [BodenmillerGroup/imcRtools#46]
The function does not handle the edge case if one of the CellTypes/labels has only one cell present in an ROI with no neighbors in expansion threshold. Throws an error in:

dat_stat[is.na(dat_baseline$ct), 
                c("p_gt", "p_lt", "ct", "interaction", 
                  "p", "sig", "sigval") := NA]

(Works great otherwise, thanks for sharing)

**Comment by erikgerdtsson** [comment]
Error in `[.data.table`(dat_stat, is.na(dat_baseline$ct), `:=`(c("p_gt",  : 
  i evaluates to a logical vector length 1071 but there are 1089 rows. Recycling of logical i is no longer allowed as it hides more bugs than is worth the rare convenience. Explicitly use rep(...,length=.N) if you really need to recycle.

**Comment by nilseling** [comment]
Hi @erikgerdtsson 
Thanks for reporting this! Could you please let me know which version of the package you are using? I'll look into this next week.

**Comment by erikgerdtsson** [comment]
> Hi @erikgerdtsson
> Thanks for reporting this! Could you please let me know which version of the package you are using? I'll look into this next week.

1.0.0

**Comment by nilseling** [comment]
Hi @erikgerdtsson 
#47 should have fixed this. The output now contains all possible label pairs across all images. Non existing labels per image are marked as `NA`.
Thanks again for raising the issue.

**Comment by roseisgold** [comment]
Hi! We are running version 1.4.2 and are coming across a similar error as above with the testInteractions() function. Feeling quite stuck. We will open a new issue but wanted to see if you had any advice for how to circumvent this! Thanks :)

**Comment by nilseling** [comment]
Hi @roseisgold 

could you please share your `SingleCellExperiment` or `SpatialExperiment` with me at nils.eling@uzh.ch? I'd like to investigate this issue.

**Comment by nilseling** [comment]
After email contact this should have been resolved now in #103
