### ISSUE TITLE
NeighbouRhood files

### ISSUE THREAD

**Issue by aleixriusr** [BodenmillerGroup/imcRtools#53]
Hi,

I would like to do a neighbourhood analysis, but I am having some issues with the input files.
I have done some clustering with FlowJo (using the fcs files exported with Histocat). But I have different cell (objects) numbers that in the file created in the last step of the IMCsegmentationpipeline. Also, the CellID that I have from histocat and the X/Y coordantes, doesn't match with the "Object number" and "Location_Center_X/Y"

Is it possible to use the neighbouRhood tool from a clustering done with some other software?

Thanks so much.

Best regards,
Aleix

**Comment by nilseling** [comment]
Hi @aleixriusr 
the `testInteractions` function takes a [SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html) or [SpatialExperiment](https://bioconductor.org/packages/release/bioc/html/SpatialExperiment.html) object as input. You can specify the `label` parameter to use the `colData` entry which holds your cell labels. This can be any clustering that you have performed elsewhere. If you are not using the output of the [ImcSegmentationPipeline](https://github.com/BodenmillerGroup/ImcSegmentationPipeline) or [steinbock](https://github.com/BodenmillerGroup/steinbock) you will need to construct your own spatial interaction graph via the `buildSpatialGraph` function. 

As for the differences between the output of the IMC Segmentation Pipeline and histoCAT: I'm not familiar with the internals of histoCAT and you can raise an issue there: https://github.com/BodenmillerGroup/histoCAT/issues

Best,
Nils

**Comment by aleixriusr** [comment]
Hi Nils,

thanks so much for the fast answer!
As I uderstand, it should not be too dificult (I am just starting with R scripts). So, I should first generate the spatial interactions (buidSpatialGraph) and afterwards the testInteractions function using the colData to assign the parameter that corresponds to my clustering.

Just one more question. I don't completly understand the output. If I would like to generate a heatmap (similar to histocat), I should use the p_gt as positive values (more interactions than a random distribution) and the p_lt as a negative (less than in random distribution)?

Best,
Aleix

**Comment by nilseling** [comment]
Hi @aleixriusr 

yes, that sounds right. For general instructions on how to use the `SingleCellExperiment` container, please refer to [here](https://bioconductor.org/books/release/OSCA/).

As seen from the [documentation](https://bodenmillergroup.github.io/imcRtools/reference/testInteractions.html), the output contains `sigval` which indicates if cell types interact more or less often compared to what would be expected by chance. This is the value that you can use to aggregate across all images (assuming this is what the heatmap in histocat is). 

Best,
Nils
