### ISSUE TITLE
Change regex of readSCEformTXT function

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/imcRtools#61]
It's safer to select the last entry of the `[A-Z]{1}[a-z]{0,1}[0-9]{2,3}` regex call.

**Comment by raymond301** [comment]
Could this be related to a bug I just ran into?

I have the provided data for the tutorial

> options(timeout=420)
> download.file("https://zenodo.org/record/5949116/files/compensation.zip","data/compensation.zip")
> unzip("data/compensation.zip", exdir="data", overwrite=TRUE)
> unlink("data/compensation.zip")

Then by default with no modifications on this code.
```r
# Create SingleCellExperiment from .txt files
sce <- readSCEfromTXT("data/compensation/") 
```

I get this error

> 
> Error in .valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols, : Not all names match the pattern (mt)(mass).
> TRACEBACK 
> 3.  stop("Not all names match the pattern (mt)(mass).")
> 2.  valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols, verbose, read_metal_from_filename)
> 1    readSCEfromTXT("data/compensation/")

**Comment by nilseling** [comment]
Are you using `imcRtools` version 1.0.2 from Bioconductor? Have a look at the [prerequisites](https://bodenmillergroup.github.io/IMCDataAnalysis/prerequisites.html) to see which software versions you need to reproduce the workflow. The current development version from Github should read in the data without errors.

**Comment by raymond301** [comment]
Yes, 1.0.2 from Bioconductor, that is correct.

My sessionInfo
```
other attached packages:
 [1] BiocParallel_1.28.3         cytomapper_1.6.0            EBImage_4.36.0              imcRtools_1.0.2             SpatialExperiment_1.4.0    
 [6] SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0 Biobase_2.54.0              GenomicRanges_1.46.1        GenomeInfoDb_1.30.1      
```  
I see...I'll update version and try again.

**Comment by nilseling** [comment]
Done in #65
