### ISSUE TITLE
clustered_neighbors

### ISSUE THREAD

**Issue by sailseem** [BodenmillerGroup/imcRtools#62]
Dear developer,

I have one question about clustered_neighbors in the example figure below. The number 1/2/3 indicates the average neighbors of each node?
Thanks in advance for your answer.

![image](https://user-images.githubusercontent.com/72428172/160036898-e6542127-ccc6-4999-a1b5-7ef7d6bab04f.png)

**Comment by nilseling** [comment]
Hi @sailseem 
here the edges between cells are colored based on cell metadata. It is not related to any property of the graph but solely relate to metadata of the "from" cell. I only used this example to highlight how to add the information of two metadata entries to the plot. But I would recommend that you only work with coloring the cells based on their metadata. Does this make sense?

**Comment by nilseling** [comment]
Assuming the answer resolved the issue
