### ISSUE TITLE
Cannot readSCEfromTXT

### ISSUE THREAD

**Issue by l2baeriswyl** [BodenmillerGroup/imcRtools#64]
> sce <- readSCEfromTXT("/Volumes/Lacie/SchenkLab/IMC/220106_21_08_B_PDAC_TMA/")
 
Error in .valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols,  :                                                                            
  Not all names match the pattern (mt)(mass).

**Comment by nilseling** [comment]
Have a look at #61 - could you please install the development version from Github? But since many people have issues with this I will push to Bioc release soon.

**Comment by l2baeriswyl** [comment]
I've got the same error with the development version from Github

**Comment by nilseling** [comment]
Oh ok, interesting. Could you please post the names of your txt files here?

**Comment by nilseling** [comment]
Could you please try again with the newest development version? In #65 I specified that the `readSCEfromTXT` function uses the last occurrence of the metal isotope pattern from the file name. This should be the ROI name that you specified when acquiring the spillover slide.

**Comment by l2baeriswyl** [comment]
Now I get a different error message: Error in .valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols,  : 
  Not all spotted channels were acquired.

**Comment by l2baeriswyl** [comment]
Now I get a different error message: 
Spotted channels:  D10, G10, J10, B11, E11, Q11, F12, G13, P13                                                                                          
Acquired channels:  Ar80, I127, Xe131, Xe134, La138, Pr141, Nd142, Nd143, Nd144, Nd145, Nd146, Sm147, Nd148, Sm149, Nd150, Eu151, Sm152, Eu153, Sm154, Gd155, Gd156, Gd158, Tb159, Gd160, Dy161, Dy162, Dy163, Dy164, Ho165, Er166, Er167, Er168, Tm169, Er170, Yb171, Yb172, Yb173, Yb174, Lu175, Yb176, G190, Ir191, Ir193, Pb208
Channels spotted but not acquired:  D10, G10, J10, B11, E11, Q11, F12, G13, P13
Channels acquired but not spotted:  Ar80, I127, Xe131, Xe134, La138, Pr141, Nd142, Nd143, Nd144, Nd145, Nd146, Sm147, Nd148, Sm149, Nd150, Eu151, Sm152, Eu153, Sm154, Gd155, Gd156, Gd158, Tb159, Gd160, Dy161, Dy162, Dy163, Dy164, Ho165, Er166, Er167, Er168, Tm169, Er170, Yb171, Yb172, Yb173, Yb174, Lu175, Yb176, G190, Ir191, Ir193, Pb208Fehler in .valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols,  : 
  Not all spotted channels were acquired.

**Comment by nilseling** [comment]
Ok, could you please post the names of your .txt files here? The `readSCEfromTXT` also takes a named list as input. The names of the individual entries indicate the spotted metal. This was implemented in cases where the metal name cannot be read in from the file name.

**Comment by l2baeriswyl** [comment]
220110_B2_38.txt
220110_B8_2.txt
220110_B11_3.txt
220110_C3_4.txt
220110_D10_5.txt
220110_E2_6.txt
220110_E5_7.txt
220110_E8_8.txt
220110_E11_9.txt
220110_F3_11.txt
220110_F12_10.txt
220110_G10_13.txt
220110_G13_12.txt
220110_H2_14.txt
220110_H5_15.txt
220110_I3_16.txt
220110_I6_17.txt
220110_J4_18.txt
220110_J7_19.txt
220110_J10_20.txt
220110_K2_21.txt
220110_K8_22.txt
220110_L3_23.txt
220110_L9_24.txt
220110_M4_25.txt
220110_M7_26.txt
220110_N2_27.txt
220110_N8_28.txt
220110_P7_29.txt
220110_P13_30.txt
220110_Q2_31.txt
220110_Q8_32.txt
220110_Q11_33.txt
220110_S7_34.txt
220110_T2_35.txt
220110_U3_36.txt
220110_U9_37.txt

**Comment by nilseling** [comment]
Ok that explains the error. From the documentation:

This function aggregates these measurements into a single SingleCellExperiment object. For this, two inputs are possible:

1. `x` is a path: By default all .txt files are read in from the specified path. Here, the path should indicate the location of the spillover slide measurement. The file names of the .txt file must contain the spotted metal isotope name in the format (mt)(mass) (e.g. Sm152 for Samarium isotope with the atomic mass 152). Internally, the last occurrence of such a pattern is read in as the metal isotope name and stored in the `colData(sce)$sample_id` slot.

2. `x` is a named list: If there are issues with reading in the metal isotope names from the .txt file names, the user can provide a list for which each entry contains the contents of a single .txt file. The names of the list must indicate the spotted metal in the format (mt)(mass). These names will be stored in the `colData(sce)$sample_id` slot.

When `read_metal_from_filename = FALSE`, the function will not attempt to read in the spotted metal isotopes from the file or list names. Therefore, only the sample_id will be set based on the file/list names.

Your file names do not include the spotted metal isotope. Please use (2) and provide the spotted isotope names as names of the list object.

**Comment by l2baeriswyl** [comment]
Thank you for your answer. 
I tried (2) and got following error:
> cur_file_names <- list.files("/volumes/Lacie/SchenkLab/IMC/220106_21_08_B_PDAC_TMA/txt/", pattern = ".txt", full.names = TRUE)
> cur_files <- lapply(cur_file_names, read.delim)
> names(cur_files) <- sub(".txt", "", basename(cur_file_names))
> sce <- readSCEfromTXT(cur_files)
Fehler in .valid.readSCEfromTXT.input(txt_list, cur_names, metadata_cols,  : 
  Not all names match the pattern (mt)(mass).

**Comment by nilseling** [comment]
Yes, the names of the list need to indicated the spotted metal (e.g. `In113`). The names that you are setting are of the format `220110_B2_38` - this is not a valid metal name. The question is which metal have you spotted in ROI `B2_38`. Please have a look at the example spillover data here: https://zenodo.org/record/5949116 (the file called compensation.zip).

**Comment by nilseling** [comment]
I assume this has been resolved
