### ISSUE TITLE
patchDetection fucntion with area output or patch area calculation

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/imcRtools#80]
Hi Nils,
wondering if it would be worth it to implement a calculation of the area of each patch either produced by the patchDetection function or a separate function. This would allow calculation of compartmentalized cellular densities.

**Comment by nilseling** [comment]
Would this work for you?

```
df <- data.frame(patch_id = c(1, 1, 1, NA, NA, NA, 2, 2, 2), area = rnorm(9))
aggregate(df$area, by = list(df$patch_id), FUN = "sum")
```

**Comment by SchulzDan** [comment]
actually not, I am more thinking about the area of he whole compartment. so something like the area of the polygon

**Comment by nilseling** [comment]
Sounds good! I'll add it soon

**Comment by nilseling** [comment]
Just to track it here. It doesn't make sense to compute it in `patchDetection` as the polygon might expand across the image border. I will need to write a second function that re-constructs a polygon and measures the size.

**Comment by nilseling** [comment]
`imcRtools` now exports the `patchSize` function in `v1.3.6` via #81. Please reopen if you have issues with this.
