### ISSUE TITLE
Rotate images from .txt IMC file

### ISSUE THREAD

**Issue by AlessiaCaramello** [BodenmillerGroup/imcRtools#85]
Hello!

I would like to rotate IMC images of either 90, 180 or 270 degrees starting from the .txt file. I've been trying to modify the X Y coordinates but the image still gets processed with the original orientation. I've also tried sorting the rows based on the new X and Y coordinates, while keeping Z, Start_push, End_push and Pushes_duration columns unchanged but still no luck. Do you have any suggestions on how to do this?

Thanks a lot for your help!

**Comment by nilseling** [comment]
Hi @AlessiaCaramello,

I believe you are using the `readImagefromTXT` function, right? You can then perform spatial operations using `EBImage` https://rdrr.io/bioc/EBImage/man/spatial.html I think the line you want to call is `images <- endoapply(images, rotate, angle=90)` (not tested)

**Comment by AlessiaCaramello** [comment]
Hi @nilseling, 

thanks for your quick reply! I tried your code and it's not giving me any errors, but not sure if it actually rotated the image. Is there a way to export the CytoImageList file to a .txt or a .tiff file?

Thanks a lot for your help!

Alessia

**Comment by nilseling** [comment]
You can first visualize the images before and after rotation (https://bodenmillergroup.github.io/IMCDataAnalysis/image-visualization.html) and write them out as tiff files (https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html#write-out-compensated-images)

**Comment by AlessiaCaramello** [comment]
Thanks a lot, this worked well!
Last question, can I use `witeImage` to save only specific channels as separate .tiff files? I was looking into `plotPixels` too but can't really make it work. 
Thanks a lot for your help again!

**Comment by AlessiaCaramello** [comment]
Great idea! It worked well.
Thanks a lot for your help again!

**Comment by nilseling** [comment]
That's great! Closing now
