### ISSUE TITLE
Suggest to fix aspect ratio by default

### ISSUE THREAD

**Issue by shazanfar** [BodenmillerGroup/imcRtools#86]
Hi Nils,

Thanks for the wonderful demo! I suggest adding `theme(aspect.ratio = 1)` to each call to `plotSpatial` in imcRtools, ideally setting this as a default behaviour to the function. The reason is so that the widths/heights of the spatial plots stay consistent with the original tissue. Thanks!

Best,
Shila

**Comment by nilseling** [comment]
Thanks @shazanfar, will definitely add this!

**Comment by nilseling** [comment]
Done in #90 by changing the defaults `scales = "fixed"` and adding `theme(aspect.ratio = 1)` in `plotSpatial`.
