### ISSUE TITLE
Error when using DittoSeq/Heatmap plots

### ISSUE THREAD

**Issue by jweis3** [BodenmillerGroup/imcRtools#88]
Thanks for the great vignettes! When running imcRtools on my own dataset, following Phenograph clustering I encounter the following error when attempting to generate a heatmap via dittoHeatMap() grouping by cluster. 

Error in .get_heatmap_data(object, genes, metas, assay, slot, cells.use) :
No target genes/metadata features have non-zero values in the 'cells.use' subset

dittoHeatmap(section70[,cur_cells], 
             genes = rownames(section70)[rowData(section70)$use_channel],
             assay = "exprs", scale = "none",
             heatmap.colors = viridis(100), 
             annot.by = "pg_clusters",
             annot.colors = c(dittoColors(1)[1:length(unique(section70$pg_clusters))]))

Session Info: 
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

using imcRtools 1.0.2

**Comment by nilseling** [comment]
I have a strong feeling that this relates to https://github.com/dtm2451/dittoSeq/issues/102. Could it be that `colnames(section70)` are not set?

**Comment by jweis3** [comment]
Yep, that was the reason why it wasn't working, thanks!
