### ISSUE TITLE
minDistToCells - Error

### ISSUE THREAD

**Issue by StefanosVoglis** [BodenmillerGroup/imcRtools#91]
Hi Nils,
as discussed:

`sce <- minDistToCells(sce, 
                      name = "distToTumorPatch",
                      x_cells = !is.na(sce$patch_id), 
                      img_id = "image_id")
`
                      
Produces the following error message:

> Error: BiocParallel errors
  1 remote errors, element index: 316
  133 unevaluated and other errors
  first remote error:
Error in distance_columns(dist_mat, column_indices = non_patch_cells): (get_dists.c:148) Failed assert: len_column_indices > 0.

`unique(sce$image_id)[316]`

... contains only few cells which are all assigned to the same patch:

`table(sce$cl_all[sce$image_id == unique(sce$image_id)[316]])`

    B cells       CD4Tc        DPTc     Myeloid Neutrophils       Tumor    Vascular 
          2           1           1          12          25        3223          11 
`table(sce$patch_id[sce$image_id == unique(sce$image_id)[316]])`

20921 
 3275

_imcRtools 1.4.1
BiocParallel 1.32.1_

Cheers, Stefanos

**Comment by nilseling** [comment]
@SchulzDan you wanna take this? ;)

**Comment by nilseling** [comment]
Hi @StefanosVoglis I think this should be resolved with the newest version. Please install from GitHub and let us know if it works

**Comment by StefanosVoglis** [comment]
Hi @nilseling,
just tested it. Now it works!
Many thanks

**Comment by nilseling** [comment]
That's great! I just pushed a bug fix to Bioconductor and will close the issue now.
