### ISSUE TITLE
read_steinbock for multiple folders

### ISSUE THREAD

**Issue by paulrbuckley-kcl** [BodenmillerGroup/imcRtools#93]
Hi,

I have a large number of folders upon which I have used steinbock to process. I'd like to read these all in for analysis into one spe object.
manually, I could do:

`test1 = read_steinbock("path1")`
`test2 = read_steinbock("path2")`
`combined = cbind(test1, test2)`

and get the object i desire. For large numbers of folders however this becomes an issue. I have tried multiple ways of doing this using Map, lapply etc, but cannot get this to work..

I'm wondering if there is a simple way to read >1 steinbock folder that I am missing for large numbers of folders?

Apologies if i'm being dim!

**Comment by paulrbuckley-kcl** [comment]
ignore this - i've done it. use a foreach loop with .combine="cbind" works properly

**Comment by nilseling** [comment]
Ok, great! I would have proposed (not tested):

```
folders <- list.files("path/to/folders", full.names = TRUE)

spes <- lapply(folder, read_steinbock)

spe <- do.call(cbind, spes)
```

**Comment by paulrbuckley-kcl** [comment]
great shout.. I was being dim!
